---
- name: Fetch RDS DB config from SSM
  vars:
    param_names:
      host:       "/rds/mysql/host"
      user:       "/rds/mysql/username"
      password:   "/rds/mysql/password"
      db_name:    "/rds/mysql/db_name"
      db_url:     "/rds/mysql/db_url"

  block:
    - name: Fetch all RDS parameters
      set_fact:
        rds_params: >-
          {{
            dict(param_names.keys() |
              zip(param_names.values() |
                map('extract',
                    lookup('community.aws.aws_ssm',
                           param_names.values(),
                           decrypt=true,
                           region=aws_region
                    )
                )
              )
            )
          }}

    - name: Set DB variables as facts
      set_fact:
        database:
          host:       "{{ rds_params.host }}"
          user:       "{{ rds_params.user }}"
          password:   "{{ rds_params.password }}"
          name:       "{{ rds_params.db_name }}"
          db_url:     "{{ rds_params.db_url }}"
