- name: Deploy Gitea on ephemeral agent
  hosts: all
  become: true
# playbooks/deploy/playbook.yaml
- name: Full Gitea Deployment
  hosts: all
  become: true
  vars_files:
    - /tmp/bootstrap_vars.yml
    - "{{ playbook_dir }}/../../config/vars.yml"

  tasks:
    - import_tasks: "{{ playbook_dir }}/../../tasks/fetch_ssm_db.yml"
    - import_tasks: "{{ playbook_dir }}/../../tasks/deploy_gitea.yml"

  handlers:
    - name: Restart Gitea
      systemd:
        name: gitea
        state: restarted
        enabled: yes
