image:
  repository: jenkins/jenkins
  tag: lts
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  agentPort: 50000
  nodePort: 30080  

persistence:
  enabled: true
  storageClass: standard
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  existingClaim: ""  


resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

adminCredentials:
  user: admin
  password: admin

controller:
  serviceAccount:
    create: false   # No queremos que Helm cree uno nuevo
    name: jenkins