- name: Full Gitea deployment on GCP VM via gcloud and SSM fetch
  hosts: localhost
  gather_facts: false

  vars:
    aws_region: "us-east-1"
    gcp_zone: "us-central1-a"
    docker_compose_file: "docker-compose.yml"

  vars_files:
    - /tmp/bootstrap_vars.yml
    - "{{ playbook_dir }}/../../config/vars.yml"

  tasks:
    - import_tasks: "{{ playbook_dir }}/../../tasks/fetch_gcp_id.yaml"
    - import_tasks: "{{ playbook_dir }}/../../tasks/deploy_gitea_docker.yaml"
  # - import_tasks: "{{ playbook_dir }}/../../tasks/setup_database.yml"

  handlers:
    - name: Restart Gitea container
      shell: |
        gcloud compute ssh {{ gcp_vm_name }} \
          --project={{ gcp_project }} \
          --zone={{ gcp_zone }} \
          --tunnel-through-iap \
          --impersonate-service-account={{ impersonated_sa }} \
          --command="docker restart gitea"
      listen: Restart Gitea
